solution was added
mate-academy/react_movies-list-filter pull request #1052
Opened 2022-10-24 20:21 UTC by Maksym845

- [DEMO LINK](https://Maksym845.github.io/react_movies-list-filter/)

2022-10-29 17:45 UTC, Yeliseiev approved these changes
An interesting solution. But it seems to me that it is better the already filtered list provide to the component

2022-11-01 10:19 UTC, sergii-nosachenko requested changes

2022-11-01 10:19 UTC, sergii-nosachenko commented on src/App.tsx
> +        />
No need to use filter logic inside MovieList component. Also your task says you need to create state variable with `visibleMovies` and pass it here as props.

2022-11-01 10:19 UTC, sergii-nosachenko commented on src/components/MoviesList/MoviesList.tsx
> +    }).map(movie => (
This function belongs to parent component. Also create create constants f.e. `descriptionNormalized` and use it. Additional lines of code but a huge improvement in readability.

2022-11-01 17:09 UTC, sergii-nosachenko approved these changes
Awesome 🔥🔥🔥

2023-04-28 17:21 UTC, closed without merging