implemented task
mate-academy/react_movies-list-filter pull request #1113
Opened 2022-10-29 15:44 UTC by oleksandr-korobko

[DEMO LINK](https://oleksandr-korobko.github.io/react_movies-list-filter/)

2022-10-29 15:45 UTC, oleksandr-korobko commented
[DEMO LINK](https://oleksandr-korobko.github.io/react_movies-list-filter/)

2022-10-31 13:37 UTC, avkovlit approved these changes
Cool!!!

2022-11-01 20:48 UTC, Anna-Tkachenko requested changes

2022-11-01 20:48 UTC, Anna-Tkachenko commented on src/App.tsx
> +    const filtredMovies = moviesFromServer.filter(({ title, description }) => {
will be better to move filtering inside set state function, because you want to set new state according to the current one

2022-11-03 01:08 UTC, closed without merging