done
mate-academy/react_movies-list-filter pull request #1139
Opened 2022-11-21 13:21 UTC by p-omogit-e

[DEMO LINK](https://p-omogit-e.github.io/react_movies-list-filter/)

2022-11-22 09:21 UTC, vlad-demchuk requested changes

2022-11-22 09:21 UTC, vlad-demchuk commented on src/App.tsx
> +      return 1;
don't do the same twice (use a separate function) and remove `eslint-disable`)

2022-11-22 09:21 UTC, vlad-demchuk commented on src/App.tsx
> +                }}
use a separate handle function

2022-11-24 08:56 UTC, tetiana-ivanchenko requested changes

2022-11-24 08:56 UTC, tetiana-ivanchenko commented on src/App.tsx
> +    return 0;
```suggestion
    return obj.toLocaleLowerCase().includes(query.toLocaleLowerCase());
```

2022-11-24 08:56 UTC, tetiana-ivanchenko commented on src/App.tsx
> +  function isInsclude(obj: string): number {
variable name: obj
type: string

logical?

2022-11-24 08:56 UTC, tetiana-ivanchenko commented on src/App.tsx
> +  });
```suggestion
  visibleFilms = visibleFilms.filter((movie) => (
    isInsclude(movie.title) || isInsclude(movie.description)
  ));
```

2022-11-28 08:51 UTC, tetiana-ivanchenko approved these changes

2025-12-17 21:30 UTC, closed without merging