Solution
mate-academy/react_movies-list-filter pull request #1415
Opened 2023-03-10 15:10 UTC by stanislavcodes

[DEMO LINK](https://stanislavcodes.github.io/react_movies-list-filter/)

2023-03-13 15:11 UTC, milenadiamonds1 approved these changes
GJ but let's use helper functions)

2023-03-13 15:11 UTC, milenadiamonds1 commented on src/App.tsx
> +                onChange={(event) => setQuery(event.target.value)}
why don't add helper func and use distructuring like { value } = event.target?

2023-03-14 12:59 UTC, illiarerun requested changes

2023-03-14 12:59 UTC, illiarerun commented on src/App.tsx
> +      const isInDescription = description.toLowerCase().includes(keyword);
you share the same logic  - `toLowerCase` and `includes` between title and description comparison, create helper func for it

2023-03-14 12:59 UTC, illiarerun commented on src/App.tsx
> +  const visibleMovies: Movie[] = [...moviesFromServer]
why do you filter copy?

2023-03-14 12:59 UTC, illiarerun commented on src/App.tsx
> +  const visibleMovies: Movie[] = [...moviesFromServer]
also, there's no need for explicitly setting type here
```suggestion
  const visibleMovies = [...moviesFromServer]
```

2023-03-17 11:43 UTC, illiarerun approved these changes

2026-07-06 09:21 UTC, closed without merging