done
mate-academy/react_movies-list-filter pull request #144
Opened 2020-10-26 16:55 UTC by aionova

[DEMO LINK](https://aionova.github.io/react_movies-list-filter/)

2020-10-26 17:14 UTC, yazheviks approved these changes
Отлично)

2020-10-27 08:35 UTC, Vladimir-Beliy requested changes

2020-10-27 08:35 UTC, Vladimir-Beliy commented on src/App.js
> +    });
```suggestion
    this.setState({
      query: value,
    });
```
также понятнее)

это было бы полезно если бы у тебя было несколько инпутов и их обрабатывала одна функция

2020-10-27 11:58 UTC, Vladimir-Beliy approved these changes

2023-09-27 08:10 UTC, closed without merging