solution
mate-academy/react_movies-list-filter pull request #1467
Opened 2023-03-26 12:50 UTC by vadym4che

[DEMO LINK](https://vadym4che.github.io/react_movies-list-filter/)

2023-03-29 20:17 UTC, Andr1yK requested changes

2023-03-29 20:17 UTC, Andr1yK commented on src/App.tsx
> +                onChange={(event) => handleSearch(event)}
```suggestion
                onChange={handleSearch}
```

2023-04-02 07:35 UTC, vadym4che commented on src/App.tsx
> +  }, [query]);
I apologize, - I was just playing with script and have forgotten to remove this childishness

2023-04-02 07:44 UTC, vadym4che commented on src/App.tsx
> +                onChange={(event) => handleSearch(event)}
unwrapped

2023-04-02 07:45 UTC, vadym4che commented on src/App.tsx
> +  const [moviesToShow, setMoviesToShow] = useState(moviesFromServer);
done - now rerendering happens only when this.state.query has been changed

2023-04-02 12:57 UTC, Andr1yK approved these changes

2024-12-09 10:33 UTC, closed without merging