solution
mate-academy/react_movies-list-filter pull request #1761
Opened 2023-12-10 22:06 UTC by Timi2424

[DEMO LINK](https://Timi2424.github.io/react_movies-list-filter/)

2023-12-10 22:21 UTC, Timi2424 commented
I didn't need apply preventDefault, because we don't sumbit a form in this example, my bad

2023-12-11 09:06 UTC, szymanski-marcin requested changes
Can't check your demo link. Try npm run deploy and re-request review after that.

2023-12-11 09:51 UTC, mvjl000 requested changes

2023-12-11 09:51 UTC, mvjl000 commented on src/App.tsx
> +  );
You could move it out of the component and just invoke it in the jsx

2023-12-11 09:51 UTC, mvjl000 commented on src/App.tsx
> +  };
No need for this handler and form either. Input will do just fine

2023-12-11 09:51 UTC, mvjl000 commented on src/App.tsx
> +                  onChange={(event) => setQuery(event.target.value.trim())}
Create a handler function for this onChange

2023-12-11 10:59 UTC, mbruhler approved these changes

2024-07-05 16:37 UTC, closed without merging