solved
mate-academy/react_movies-list-filter pull request #299
Opened 2021-04-09 12:51 UTC by JohnCrownHC

[DEMO LINK](https://JohnCrownHC.github.io/react_movies-list-filter/)

2021-04-09 13:06 UTC, Alex-Levch approved these changes
Very nice!

2021-04-12 06:56 UTC, danheim requested changes

2021-04-12 06:56 UTC, danheim commented on src/components/SearchBar/SearchBar.jsx
> +    list(value);
плохое название для функции, непонятно что она делает

2021-04-12 08:41 UTC, danheim approved these changes
Great

2024-04-18 12:31 UTC, closed without merging