solution
mate-academy/react_movies-list-filter pull request #453
Opened 2021-09-12 11:48 UTC by Vova-Stoliar

[DEMO LINK](https://Vova-Stoliar.github.io/react_movies-list-filter/)

2021-09-13 13:10 UTC, evgen1sider reviewed
десь потеряв файл MovieList))

2021-09-14 08:50 UTC, danheim requested changes

2021-09-14 08:50 UTC, danheim commented on src/App.tsx
> +};
```suggestion
type State = {
  query: string;
  movieStorage: Movie[];
};
```

2021-09-14 08:50 UTC, danheim commented on src/App.tsx
> +  });
remove it from the component

2021-09-14 08:50 UTC, danheim commented on src/App.tsx
> +    movieStorage: this.moviesFromServerClone,
map directly here

2021-09-17 07:10 UTC, danheim approved these changes

2023-01-12 09:40 UTC, closed without merging