Task was solved
mate-academy/react_movies-list-filter pull request #526
Opened 2021-11-11 17:46 UTC by cyb1ove

[DEMO LINK](https://cyb1ove.github.io/react_movies-list-filter/)

2021-11-11 17:54 UTC, MariiaObraztsova requested changes
It doesn't work if I enter upper case letters

2021-11-11 18:10 UTC, MariiaObraztsova approved these changes

2021-11-12 11:20 UTC, solaryasha approved these changes

2021-11-12 11:20 UTC, solaryasha commented on src/App.tsx
> +                  onChange={(event) => this.updateState(event)}
```suggestion
                  onChange={this.updateState}
```

2021-11-12 11:20 UTC, solaryasha commented on src/App.tsx
> +    return args.some(value => value.toLowerCase().includes(this.state.query));
🔥

2025-01-20 16:29 UTC, closed without merging