solution
mate-academy/react_movies-list-filter pull request #606
Opened 2022-01-24 09:43 UTC by andrii-koptiev

[DEMO LINK](https://andrii-koptiev.github.io/react_movies-list-filter/)

2022-01-24 10:18 UTC, MaksimusCRS approved these changes

2022-01-24 10:18 UTC, MaksimusCRS commented on src/App.tsx
> +    ));
Очень тяжело читать такой код, я бы рекомендовал вынести некие действия в отдельные функции, к примеру, сделать функцию для проверки, есть ли слово в заголовке и ещё одну функцию, есть ли слово в описании, а потом в функции visibleMovies вызывать их для фильтра. Так другим разработчикам будет понятна твоя логика и твой код, да и проще рефакторить потом будет.

P.S. Сам себя ловлю очень часто на таких штуках, сначала пишу в одну строку всё, а потом уже переписываю по функциям)

2022-01-26 11:48 UTC, danheim requested changes

2022-01-26 11:48 UTC, danheim commented on src/App.tsx
> +    const visibleMovies = movies.filter(movie => (
вынеси это в отдельный метод, не пиши много логики в render
```suggestion
    const visibleMovies = this.getVisibleMovies();
```

2022-01-26 11:48 UTC, danheim commented on src/App.tsx
> +      || movie.description.toLowerCase().includes(query.toLowerCase())
согласен с Максимом, сложно читать, попробуй упростить визуально

2022-01-26 13:28 UTC, andrii-koptiev commented on src/App.tsx
> +    ));
make sense

2022-01-26 13:29 UTC, andrii-koptiev commented on src/App.tsx
> +    const visibleMovies = movies.filter(movie => (
make sense

2022-01-26 13:29 UTC, andrii-koptiev commented on src/App.tsx
> +      || movie.description.toLowerCase().includes(query.toLowerCase())
make sense

2022-01-26 19:55 UTC, danheim approved these changes

2022-01-26 19:55 UTC, danheim commented on src/App.tsx
> +  );
не рекомендую это выносить отдельными методами, но ок

2022-01-26 20:02 UTC, andrii-koptiev commented on src/App.tsx
> +  );
принял. спс

2023-09-26 21:08 UTC, closed without merging