solution
mate-academy/react_movies-list-filter pull request #619
Opened 2022-01-25 15:22 UTC by mykola-koval

[DEMO LINK](https://mykola-koval.github.io/react_movies-list-filter/)

2022-01-26 09:25 UTC, Toros-Zz approved these changes

2022-01-26 11:47 UTC, danheim requested changes

2022-01-26 11:47 UTC, danheim commented on src/App.tsx
> +    });
вынеси логику фильтра в отдельный метод
```suggestion
    const visibleMovies = this.getVisibleMovies();
```

2022-01-27 19:21 UTC, mykola-koval commented on src/App.tsx
> +    });
Done!

2022-01-28 09:00 UTC, danheim approved these changes

2023-03-02 07:59 UTC, closed without merging