solution
mate-academy/react_movies-list-filter pull request #691
Opened 2022-04-01 19:19 UTC by AnnSerdechna

[DEMO LINK](https://annserdechna.github.io/react_movies-list-filter/)

2022-04-03 08:28 UTC, aspurgilus approved these changes
Good work!

2022-04-04 11:52 UTC, Ihor-Karpyn requested changes

2022-04-04 11:52 UTC, Ihor-Karpyn commented on src/App.tsx
> +    || movie.description.toLowerCase().includes(query.toLowerCase()));
create function to filter and use `useMemo`

2022-04-04 15:42 UTC, Ihor-Karpyn approved these changes

2024-12-05 14:36 UTC, closed without merging