my solution
mate-academy/react_movies-list-filter pull request #845
Opened 2022-07-15 10:53 UTC by Pavlo000

[DEMO LINK](https://Pavlo000.github.io/react_movies-list-filter/)

2022-07-18 08:05 UTC, illavodonis approved these changes

2022-07-19 08:45 UTC, jstmpelowycz requested changes

2022-07-20 07:10 UTC, jstmpelowycz requested changes

2022-07-20 07:10 UTC, jstmpelowycz commented on src/App.tsx
> +      || normalizeDescription.toLowerCase().includes(normalizeSearch);
```suggestion
      return normalizeTitle.includes(normalizeSearch)
      || normalizeDescription.includes(normalizeSearch);
```

2022-07-20 07:10 UTC, jstmpelowycz commented on src/App.tsx
> +      || normalizeDescription.toLowerCase().includes(normalizeSearch);
you've already made it lowercase

2022-07-20 07:10 UTC, jstmpelowycz commented on src/App.tsx
> +  const visibleMovies = [...moviesFromServer]
```suggestion
  const [search, setSearh] = useState('');
  
  const visibleMovies = [...moviesFromServer]
```

2022-07-20 07:40 UTC, jstmpelowycz approved these changes

2024-11-26 18:27 UTC, closed without merging