added movie list filter
mate-academy/react_movies-list-filter pull request #911
Opened 2022-08-11 08:56 UTC by silchyn

[DEMO](https://silchyn.github.io/react_movies-list-filter/)

2022-08-11 10:02 UTC, LordAsmodey approved these changes
Looks good

2022-08-11 14:36 UTC, Ihor-Karpyn requested changes

2022-08-11 14:36 UTC, Ihor-Karpyn commented on src/App.tsx
> +  const visibleMovies = useMemo(() => {
add an empty line

2022-08-11 14:36 UTC, Ihor-Karpyn commented on src/App.tsx
> +    });
Move filter to separate function. Hard for understanding

2022-08-11 14:42 UTC, Ihor-Karpyn reviewed
Or smth like that

2022-08-11 14:42 UTC, Ihor-Karpyn commented on src/App.tsx
> +  }, [query]);
```suggestion
  const visibleMovies = useMemo(() => moviesFromServer.filter(movie => (
     movie.title.toLowerCase().includes(query.toLowerCase())
     || movie.description.toLowerCase().includes(query.toLowerCase())
  )), [query]);
```

2022-08-12 09:35 UTC, Ihor-Karpyn requested changes
Good job, but filter function still very ard

2022-08-12 09:35 UTC, Ihor-Karpyn commented on src/App.tsx
> +};
```suggestion
const filterMovies = (query: string) => (moviesFromServer.filter(movie => {
	const preparedQuery = query.toLowerCase();
	const title = movie.title.toLowerCase();
	const description = movie.description.toLowerCase();

  const isTitleMatched = title.includes(preparedQuery))
  const isDescriptionMatched = description.includes(preparedQuery));
  
  return isTitleMatched || isDescriptionMatched
});
```

2022-08-12 09:35 UTC, Ihor-Karpyn commented on src/App.tsx
> +  const visibleMovies = useMemo(filterMovies(query), [query]);
```suggestion
  const visibleMovies = useMemo(() => filterMovies(query), [query]);
```

2022-08-12 09:52 UTC, Ihor-Karpyn approved these changes
I like it, much better 🚀

2023-02-10 20:21 UTC, closed without merging